### ISSUE TITLE
Powershell script downloaded with .sh file extension

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-runtime#114] opened 2020-08-24 16:17 UTC
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Tuesday, August 4, 2020 6:29:15 AM_

Does this occur consistently? 
Repro steps:

1.
2.

Action: startArmLanguageServer
Error type: Error
Error Message: This extension requires .NET Core for full functionality, but we were unable to download and install a local copy for the extension. If this error persists, please see https://aka.ms/vscode-armtools-dotnet for troubleshooting tips. 
Details: dotnet.acquire returned undefined

Version: 0.12.0
OS: linux
OS Release: 3.10.0-1127.10.1.el7.x86_64
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
Object.wrapError extension.bundle.js:395:93998
Object.<anonymous> extension.bundle.js:486:771149
fulfilled extension.bundle.js:486:770045
```

</details>

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @StephenWeatherford.

---

_From @StephenWeatherford on Tuesday, August 4, 2020 10:16:29 PM_

Did the troubleshooting tips at https://aka.ms/vscode-armtools-dotnet help?

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @StephenWeatherford.

---

_From @StephenWeatherford on Monday, August 10, 2020 5:49:35 PM_

@AdamRussak I've been looking for more info about this issue, would love any additional info you can provide.  Did the troubleshooting tips help?  If so, which one?  Thanks!

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Monday, August 10, 2020 6:04:36 PM_

I closed the ticket :)
Sorry.

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @StephenWeatherford.

---

_From @StephenWeatherford on Monday, August 10, 2020 7:51:05 PM_

Does that mean you never tried again?  Thx.

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Wednesday, August 12, 2020 11:10:25 AM_

> Does that mean you never tried again? Thx.

used the extension again, hers the error:
```
Downloading .NET Core tooling version(s) 3.1.6 .... Error!
Failed to download .NET Core tooling 3.1.6:
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:46 char:9
+ say_err() {
+         ~
An expression was expected after '('.
At C:\Users\adam.russak\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-0.1.2\dist\install 
scripts\dotnet-install.ps1:47 char:67
+     printf "%b\n" "${red:-}dotnet_install: Error: $1${normal:-}" >&2
+                                                                   ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 


 Error!
Dotnet Core Acquisition Failed: undefined
```

UPDATE:
manuly install .Net Core sdk solved the issue

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @StephenWeatherford.

---

_From @StephenWeatherford on Wednesday, August 12, 2020 5:30:58 PM_

@sfoslund Sarah, why does it look like the .ps1 file is a Linux shell script?

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Wednesday, August 12, 2020 5:41:42 PM_

> @sfoslund Sarah, why does it look like the .ps1 file is a Linux shell script?

if you whant i can take a look at the PS script

**Comment by sfoslund** [comment] 2020-08-24 16:17
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @sfoslund.

---

_From @sfoslund on Wednesday, August 12, 2020 5:56:23 PM_

Interesting, it looks like the .sh script is getting downloaded but placed in a .ps1 file extension. @AdamRussak you're using linux, right? So the correct script is being downloaded but it has the wrong file extension.

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @StephenWeatherford.

---

_From @StephenWeatherford on Wednesday, August 12, 2020 5:58:48 PM_

From the paths above, he's using Windows.

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @sfoslund.

---

_From @sfoslund on Wednesday, August 12, 2020 6:01:08 PM_

Hmm, then why does the original issue metadata say linux?

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Wednesday, August 12, 2020 6:41:26 PM_

> Interesting, it looks like the .sh script is getting downloaded but placed in a .ps1 file extension. @AdamRussak you're using linux, right? So the correct script is being downloaded but it has the wrong file extension. 

I'm using a windows OS and using vs code ssh and the error happened on both of them (on windows I manually downloaded the sdk and it fixed it)
The message is from win

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @sfoslund.

---

_From @sfoslund on Wednesday, August 12, 2020 7:47:15 PM_

>The message is from win

You mean the original issue message, where it says the OS is linux, or the error message in [this comment](https://github.com/microsoft/vscode-azurearmtools/issues/898#issuecomment-672808151)?

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Thursday, August 13, 2020 7:31:58 AM_

> >The message is from win
> 
> You mean the original issue message, where it says the OS is linux, or the error message in [this comment](https://github.com/microsoft/vscode-azurearmtools/issues/898#issuecomment-672808151)?

The original was on Linux (the issue is still active there)
The later errors I posted was on windows

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @sfoslund.

---

_From @sfoslund on Thursday, August 20, 2020 7:21:06 PM_

Okay, it seems that the .sh file is getting downloaded and saved to a .ps1 file. I'm not sure how this is happening so it will require some investigation, mind if I move this over to our repo?

**Comment by sfoslund** [comment] 2020-08-24 16:18
---
**Issue moved from microsoft/vscode-azurearmtools#898**
- Please respond to @AdamRussak.

---

_From @AdamRussak on Saturday, August 22, 2020 7:13:39 PM_

was this refered to me?
if so, sure.

**Comment by sfoslund** [comment] 2021-02-25 17:11
@mairaw we've gotten a few issues that appear to be caused by the wrong install script being served from https://dot.net/v1/dotnet-install.ps1. The logs from #177 confirm that a request was sent for aka.ms/dotnet-install-script-ps1, which redirects to https://dot.net/v1/dotnet-install.ps1, but we end up getting the .sh script. Have you seen issues like this before?

**Comment by mairaw** [comment] 2021-02-25 22:30
No, but let me double check all the redirections we have in place since we moved some of these things recently.

**Comment by mairaw** [comment] 2021-02-25 23:42
I can't reproduce this and I checked that the redirect we have in place are going to the appropriate URL

![image](https://user-images.githubusercontent.com/12971179/109234108-eca94400-777f-11eb-923c-a814f8f5ccf6.png)


![image](https://user-images.githubusercontent.com/12971179/109234143-fcc12380-777f-11eb-80d6-81e6de1fd229.png)

**Comment by sfoslund** [comment] 2021-02-25 23:44
Thanks for checking @mairaw, I'll triple check things on our end then.

**Comment by anthony-c-martin** [comment] 2021-05-26 20:06
We've also just had a recent repro for this: https://github.com/Azure/bicep/issues/2839

**Comment by sfoslund** [comment] 2021-06-28 22:16
@mairaw we're still getting reports of this issue occasionally. I've double checked our telemetry and confirmed that we are always requesting the proper file extension based on OS. Do you have any other ideas on why this may be happening?

**Comment by mairaw** [comment] 2021-08-13 19:00
No ideas on why this could be happening @sfoslund. @ChrisSfanos is this something we can talk to the team responsible for these redirections? It doesn't make any sense to me why it would grab the other file.

**Comment by ChrisSfanos** [comment] 2021-08-13 19:09
We've seen some odd errors on scripts failing to get pulled during the redirects - my recommendation is not to grab scripts via redirects as it's definitely been sketchy.

**Comment by nagilson** [comment] 2022-10-11 23:57
Closing as duplicate of https://github.com/dotnet/vscode-dotnet-runtime/issues/159

**Closed by nagilson** 2022-10-11 23:57 UTC
Labels: bug, install scripts
