### ISSUE TITLE
Error when starting VS Code: Error! The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by brunocasarotti** [dotnet/vscode-dotnet-runtime#1079] opened 2023-07-17 14:42 UTC
**Repro steps:**

1. I just open VS and the error pops up. I am runing vscode remote on my wsl. The application can be built normally but this error is vey annoying.
2.  I don't know which file arguments it's referring to.

![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/20110633/395f0f68-16c6-4ddd-a1df-9051c7190fcc)

**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** 
```
TypeError: The "file" argument must be of type string. Received an instance of Object
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at normalizeSpawnArguments (node:child_process:518:3)
	at Object.spawnSync (node:child_process:786:8)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095661
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095584
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37962
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36621
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36366)
	at t.callWithErrorHandling (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37910)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095578
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095512
	at e.$vL.h (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:64085)
	at e.$vL.g (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:63073)
	at e.$vL.executeCommand (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:100:62973)
	at Object.executeCommand (/home/anonymous/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/workbench/api/node/extensionHostProcess.js:118:20971)
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.vscode-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
	at Generator.next (<anonymous>)
	at s (/home/anonymous/.vscode-server/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by baronfel** [comment] 2023-07-17 14:43
This is likely a duplicate of #1007.

**Closed by baronfel** 2023-07-17 14:43 UTC
