### ISSUE TITLE
vscode-dotnet-runtime

### ISSUE THREAD

**Issue by hornbech** [dotnet/vscode-dotnet-runtime#177] opened 2021-02-25 07:40 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Jacob Hornbech\AppData\Roaming\Code\logs\20210225T082439\exthost3\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1614238229367.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by hornbech** [comment] 2021-02-25 07:41
[DotNetAcquisition1614238229367.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/6041252/DotNetAcquisition1614238229367.txt)

**Comment by hornbech** [comment] 2021-02-25 07:42
[DotNetAcquisition1614238229367.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/6041256/DotNetAcquisition1614238229367.txt)

**Comment by sfoslund** [comment] 2021-02-25 16:56
Thanks for filing an issue, this looks like a duplicate of #114 so I'll close this one and track the issue there.

**Closed by sfoslund** 2021-02-25 16:56 UTC
Labels: bug, duplicate, install scripts
