### ISSUE TITLE
iago

### ISSUE THREAD

**Issue by iago8311** [dotnet/vscode-dotnet-runtime#1060] opened 2023-07-15 18:55 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/iago/.config/Code/logs/20230715T155512/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689447316606.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by deccer** [comment] 2023-07-16 09:39
Please attach the mentioned log file

**Comment by baronfel** [comment] 2023-07-17 14:21
Closing as duplicate of #1007

**Closed by baronfel** 2023-07-17 14:21 UTC
