### ISSUE TITLE
ilspy-vscode

### ISSUE THREAD

**Issue by RusyaevAleksandr** [dotnet/vscode-dotnet-runtime#522] opened 2022-07-09 12:57 UTC
An error occurred while installing .NET (6.0): .NET Acquisition Failed: Installation failed: Error: Command failed: powershell.exe -NoProfile -ExecutionPolicy unrestricted -Command "& { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; & 'c:\Users\Cross39\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install scripts\dotnet-install.ps1' -InstallDir 'c:\Users\Cross39\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.6' -Version 6.0.6 -Runtime dotnet } 'powershell.exe' is not recognized as an internal or external command, operable program or batch file.

**Comment by nagilson** [comment] 2022-10-14 23:02
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 23:02 UTC
