### ISSUE TITLE
"Error acquiring .NET!" when running on Windows 11 / WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by amunra** [dotnet/vscode-dotnet-runtime#480] opened 2022-06-14 11:40 UTC
My VSCode window has a red error message in the bottom blue bar.
When I click on it, I get the following log:

```
Downloading the .NET Runtime.
Downloading .NET version(s) 6.0.5 ... Error!
Failed to download .NET 6.0.5:
Command failed: "/home/adam/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/adam/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.5" -Version 6.0.5 -Runtime dotnet
/home/adam/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected


 Error!
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/adam/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/adam/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.5" -Version 6.0.5 -Runtime dotnet
/home/adam/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected
```

I'm running:
```
$ uname -r
5.10.102.1-microsoft-standard-WSL2
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by markgomez** [comment] 2022-06-14 15:59
I also came across the same errors this morning (something must've auto-updated overnight). This is how I fixed things for my particular setup:    
1. Find out which installed extension depends on `ms-dotnettools.vscode-dotnet-runtime`. A quick way to figure this out is to disable (but don't actually go through with it) `ms-dotnettools.vscode-dotnet-runtime` — a notification saying something like "Cannot disable '.NET Install Tool for Extension Authors' extension alone. 'CMake Language Support' extension depends on this."
2. With the dependent extension revealed, make note of its unique identifier (in my case it's `josetr.cmake-language-support-vscode`).
3. Because the error happens for some reason during the download and setup of .NET, and because I already have an existing installation of .NET, I used the `"dotnetAcquisitionExtension.existingDotnetPath"` setting to prevent the errors (i.e., avoid the redundant download/setup):  
```json
"dotnetAcquisitionExtension.existingDotnetPath": [
  {
    "extensionId": "josetr.cmake-language-support-vscode",
    "path": "/Users/mgomez/.dotnet/dotnet"
  }
],
```

Instead of errors, the `.NET Runtime` output now reads:  
```
Downloading the .NET Runtime.
Using configured .NET path: /Users/mgomez/.dotnet/dotnet
```

I don't know if this is a [dotnet/vscode-dotnet-runtime](https://github.com/dotnet/vscode-dotnet-runtime) issue or a [dotnet/install-scripts](https://github.com/dotnet/install-scripts) issue (in my error message, it said to report the bug at [dotnet/install-scripts](https://github.com/dotnet/install-scripts/issues)).

**Comment by vannaka** [comment] 2022-06-15 02:59
@markgomez Your solution solved this same problem for me, thanks!

I believe this issue is a result of the script `dotnet-install.sh` being a powershell script but getting executed as a bash script in WSL.

**Comment by markgomez** [comment] 2022-06-15 03:14
> I believe this issue is a result of the script `dotnet-install.sh` being a powershell script but getting executed as a bash script in WSL.

I was seeing this error on an M1 MacBook Pro, but that's interesting to hear (I haven't tested my WSL setup). Glad you got it sorted!

**Comment by MichaelSuen-thePointer** [comment] 2022-08-04 02:17
For me, It seems that the content of .ps1 file is linux shell script.
![image](https://user-images.githubusercontent.com/12868093/182748648-5c7ce885-80d8-46b7-969c-5c958591474e.png)

**Comment by nagilson** [comment] 2022-10-14 23:06
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Comment by burtonrodman** [comment] 2023-07-14 02:45
perhaps it's a different issue, but happening for me after updating to 1.80.0 with a project on a remote Dev Container running on Ubuntu Server via SSH.

**Comment by shelper** [comment] 2024-04-10 02:14
same here, with latest vscode

**Comment by nagilson** [comment] 2024-04-10 22:22
There are several errors above, which one are you experiencing? May you please file a new issue with the logs so we could investigate?

**Closed by nagilson** 2024-04-10 22:22 UTC
