### ISSUE TITLE
Failed to download .NET: Validation of .dotnet installation failed: Expected executable does not exist at 

### ISSUE THREAD

**Issue by ttanatb** [dotnet/vscode-dotnet-runtime#1693] opened 2024-03-07 19:07 UTC
### Describe the bug.

Starting up Visual Studio code, one of the extensions I use (Yarn Spinner) requested to download .NET runtime

Error acquiring .NET

Output:
```
Downloading .NET version(s) 6.0.27~x64 ..... Done!
.NET 6.0.27~x64 executable path: c:\Users\Tanat\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.27~x64\dotnet.exe

Error
Failed to download .NET 6.0.27~x64:
Validation of .dotnet installation for version 6.0.27~x64 failed: Expected executable does not exist at "c:\Users\Tanat\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.27~x64\dotnet.exe"

Error
Failed to download .NET 6.0:
.NET Acquisition Failed: Validation of .dotnet installation for version 6.0.27~x64 failed: Expected executable does not exist at "c:\Users\Tanat\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\6.0.27~x64\dotnet.exe"
```

Logs:
[20240307T190248.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/14528911/20240307T190248.zip)

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Launch workspace with [Yarn Spinner](https://marketplace.visualstudio.com/items?itemName=SecretLab.yarn-spinner) extension 

### Expected Behavior

No error from .NET

### .NET Install Tool Version

6.0.27~x64

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.87.1

**Comment by nagilson** [comment] 2024-03-20 18:54
This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/1684

**Closed by nagilson** 2024-03-20 18:54 UTC
Labels: bug
