### ISSUE TITLE
[NETE2ESDK] There is no a message of success after uninstalling the SDK via the ‘.NET Install Tool: Uninstall .NET’ command.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1920] opened 2024-08-16 08:20 UTC
### Describe the bug.

There is no a message of success after uninstalling the SDK via the ‘.NET Install Tool: Uninstall .NET’ command.

### Reproduction Steps

1.Run the command ‘.NET Install Tool: Install .NET SDK System-Wide' to install the .NET SDK and enter the newest version.
2.Open the command palette and run the ‘.NET Install Tool: Uninstall.NET’ command
3.Select the SDK to uninstall that you had installed
4.Observe

### Expected Behavior

Uninstall should succeed and show a message of success like bellow.
![image](https://github.com/user-attachments/assets/dc37ebdf-6715-40c6-88e1-b3a9ed56c525)

### Exceptions & Errors (if any)

There is no a message of success after uninstalling the SDK via the ‘.NET Install Tool: Uninstall .NET’ command.
![image](https://github.com/user-attachments/assets/680d5348-1ba9-4070-9603-c7567ab1c2f2)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.92.2

**Comment by nagilson** [comment] 2024-08-16 16:35
That seems unusual. Is this true for all OS? I was unable to reproduce this behavior. If you have a way of sharing a video, that would be helpful. The log file looks like the program never terminated but I could not reproduce this issue. The only way I can get this behavior is by closing VS Code early.

**Comment by nagilson** [comment] 2024-08-16 16:36
@v-xiaofchen

**Comment by v-xiaofchen** [comment] 2024-08-19 06:02
This is a video about the issue.
![Bug#1920](https://github.com/user-attachments/assets/bb000a4d-84a8-4d78-880f-e006d0404651)

**Comment by nagilson** [comment] 2024-08-19 17:20
Fascinating... thank you for the video. I wont block the release on this but this is worth investigating more.

**Comment by nagilson** [comment] 2024-08-19 17:20
Btw, is this only windows or also mac and linux?

**Comment by nagilson** [comment] 2024-08-19 18:30
Nvm I see it in the test plan and its all OS. I was also able to repro. Thank you

**Comment by nagilson** [comment] 2024-10-15 22:25
This was a very silly bug, must have deleted some code by accident

**Closed** 2024-10-16 18:08 UTC
Labels: untriaged, P1
