### ISSUE TITLE
vscode can't initialize and import dot-net run time in my project

### ISSUE THREAD

**Issue by codestrap97a** [dotnet/vscode-dotnet-runtime#999] opened 2023-07-11 08:12 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

dotnet acquisition does not work for me in vscode and can not download and import runtime and sdk into my project. the log file is also empty! What can i do to fix this up?

**Comment by codestrap97a** [comment] 2023-07-12 03:59
Found the problem! The main cause that the SDKs and runtime cannot be imported was the new version of C# extension in vscode which uses the LSP host. By default, the previous version was working along with Omnisharp server. I reverted the C# extension back to its stable last release and the problem disappeared, But still there is nothing in log file!!!
Hope your team to to fix that!

**Comment by baronfel** [comment] 2023-07-17 14:41
Going to close this as a duplicate of #1007 given that it's the error caused by the C# extension. As @nagilson mentioned we're working on the log file issue separately.

**Closed by baronfel** 2023-07-17 14:41 UTC
