### ISSUE TITLE
dotnet-install.sh: line 1192: link_types[$link_index]: unbound variable

### ISSUE THREAD

**Issue by NorthIsUp** [dotnet/vscode-dotnet-runtime#574] opened 2022-08-26 22:39 UTC
**Repro steps:**

1. open vs code

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.8" -Version 6.0.8 -Runtime dotnet
/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: line 1192: link_types[$link_index]: unbound variable

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/anonymous/Library/Application Support/Code - Insiders/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.8" -Version 6.0.8 -Runtime dotnet
/Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: line 1192: link_types[$link_index]: unbound variable

	at /Users/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/extension.js:2:13750

**Comment by nagilson** [comment] 2022-10-14 21:44
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 21:44 UTC
