### ISSUE TITLE
407 error: Authentication Required on acquiring install script

### ISSUE THREAD

**Issue by pmozbert** [dotnet/vscode-dotnet-runtime#77] opened 2020-05-04 11:51 UTC
407 error: Authentication Required on acquiring install script

See log files:
[DotNetAcquisition1588592996757.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/4574426/DotNetAcquisition1588592996757.txt)

**Comment by sfoslund** [comment] 2020-05-04 14:45
Hi @pmozbert, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!

**Comment by pmozbert** [comment] 2020-05-04 17:33
I followed the error reporting instructions.  If this is not enough info,
can you update the instructuons?

**Comment by sfoslund** [comment] 2020-05-04 17:36
Please check this issue body, which gives the full instruction. We aren't able to automatically populate the issue body in case your stack trace is too long so we copy is to your clipboard ¯\_(ツ)_/¯

**Comment by pmozbert** [comment] 2020-05-04 18:09
I attached the file as instructed

**Comment by sfoslund** [comment] 2020-05-04 18:14
Oh I'm sorry, I totally missed that! I'll reopen this and edit the issue body to make for easier tracking. Thanks!

**Comment by sfoslund** [comment] 2020-05-04 18:20
@pmozbert is it possible this is due to a software restriction policy? Are you able to access https://dot.net/v1/dotnet-install.ps1 or https://dot.net/v1/dotnet-install.sh directly?

**Comment by pmozbert** [comment] 2020-05-04 21:31
I just restarted vscode and there was no error.  So i guess its just one of
those weird glitches.

**Comment by pmozbert** [comment] 2020-05-04 22:19
I spoke to soon.  It's running this for a very long time.  seems hung.
`Downloading .NET Core tooling version(s) 3.1.3 .....................................................................`
I'm behind a corporate proxy that requires authentication.  That said, I've not had proxy problems with vscode when it comes to update or installing extensions.  

Possibly related,  the arm template language server is also hanging with
'Starting ARM Template Language Server'

**Comment by sfoslund** [comment] 2020-05-04 22:21
The ARM extension depends on this one so they will hang if this one does. What OS are you on? Can you access https://dot.net/v1/dotnet-install.ps1 or https://dot.net/v1/dotnet-install.sh without authentication?

**Comment by pmozbert** [comment] 2020-05-04 22:22
I get blocked by proxy for https://dot.net/v1/dotnet-install.ps1

`Web filter category: Internet Services, PUPs (potentially unwanted programs)`

But this one works - https://dot.net/v1/dotnet-install.sh   Being on windows, it doesn't help though.

**Comment by sfoslund** [comment] 2020-05-04 22:26
That's the cause then, we need access to that script to be able to install .NET. I'm not sure why it would be blocked and the .sh file isn't, but that's not helpful.

I'm not sure that this is an issue that we can fix. For now if you need a work around you can install .NET manually and point the ARM extension to that installation: https://github.com/microsoft/vscode-azurearmtools/wiki/Troubleshooting-DotNet-Acquisition#work-around-installing-dotnet-core-manually

**Comment by pmozbert** [comment] 2020-05-04 23:32
Hi,  the manual install fixed the problem.  Thanks.

**Closed** 2020-05-04 23:32 UTC
Labels: bug
