### ISSUE TITLE
libcoreclr.dylib leads to libsystem_c.dylib!abort and crashing repeatedly

### ISSUE THREAD

**Issue by winzig** [dotnet/vscode-dotnet-runtime#252] opened 2021-06-30 16:53 UTC
Initially reported to vscode an issue where `chrome_crashpad_handler` was constantly running with high CPU/disk usage here: https://github.com/microsoft/vscode/issues/127392 (and someone else reported it here: https://github.com/microsoft/vscode/issues/124713)

They looked at the attached dmp's and stated:

> Thanks for the logs, all of them point to crash in the dotnet runtime specifically a call from libcoreclr.dylib leads to libsystem_c.dylib!abort case. Since I don't have symbols for this extension binary, I can't specifically say why.

They suggested I open an issue here and attach my dmp files, so here it is.

[dmps.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/6742628/dmps.zip)

**Comment by winzig** [comment] 2021-06-30 16:58
Here are a few more .dmp's from this morning. Unlike the others I uploaded, these are from the `completed` folder, so perhaps they'll be more useful as I'm guessing they're uploaded to Microsoft's system. 

[dmps-completed.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/6742689/dmps-completed.zip)

**Comment by pascallapradebrite4** [comment] 2021-06-30 18:10
I was also advised that my problem with VS Code's Crashpad (105,780 dmps in total, so more 10,000 dmps per hour during one workday last week, fan spinning the whole day, ended up taking 20.43 gb of disk space) was seemingly caused by the `vscode-dotnet-runtime` extension.

Here are my specs:

MacBook Pro (15-inch, 2019)
CPU: 2,3 GHz 8-Core Intel Core i9
Memory: 16 GB 2400 MHz DDR4
OS: Big Sur 11.4 (20F71)

VS Code version: Code 1.57.1
OS version: Darwin x64 20.5.0

And in case it can help, here are some of my dmps as well:

[dmps.zip](https://github.com/dotnet/vscode-dotnet-runtime/files/6743085/dmps.zip)

**Comment by sfoslund** [comment] 2021-06-30 18:20
Can you please provide the vscode-dotnet-runtime logs? You can get a file path by running the report issue command: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#other-issues

**Comment by winzig** [comment] 2021-06-30 20:17
@sfoslund The file located in the specified folder (`~/Library/Application Support/Code/logs/20210630T131453/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1625084122504.txt`) is currently zero bytes in size.

**Comment by pascallapradebrite4** [comment] 2021-06-30 20:19
Hi @sfoslund ! Thanks for your help!

Sadly, the logs are completely empty on my machine - all the while the Crashpad handler is running constantly, indicating the issue(s) is presumably happening right now. I ran the command on all my windows, and all .txt reports were empty.

Given that info wasn't available, I went through a more thorough investigation on my side, since it's quite a hassle in my workday to have my disk fill up like that. I had many .NET projects and non-.NET projects opened at the same time. I closed and opened each of them one by one until I could identify a single window is causing the problem:

1. I found one window where closing it would immediately stop the Crashpad handler. Opening it would immediately start it again. My other windows didn't have that effect. (Note: I disabled all extensions and re-enable them on a workspace basis to help VS Code start faster, so it helped identifying which specific window was responsible)
2. I ran VS Code's Extensions Bisect tool, and sure enough, the extension found was `ms-dotnettools.vscode-dotnet-runtime`, which matches what the person that helped me in the original issue in VS Code said.
3. I then tried to disable the extension for that window, but couldn't, as another extension depends on it: `stripe.vscode-stripe`.
4. I then disabled `stripe.vscode-stripe` but let `ms-dotnettools.vscode-dotnet-runtime` enabled, and... the Crashpad handler wasn't running anymore.

Which is very interesting, since I never installed `ms-dotnettools.vscode-dotnet-runtime` myself, so it seems that Stripe's extension eventually added it as a dependency - likely around the time when I started noticing the problem. I went and looked in their repo, and it seems indeed they added it only 12 days ago: https://github.com/stripe/vscode-stripe/commit/0511ab41341fa8a4d697904861c1cea49d238057#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Now, the way I see it, the issue could either be in `ms-dotnettools.vscode-dotnet-runtime` and something called by `stripe.vscode-stripe` is crashing; or it's reversed, and it's `stripe.vscode-stripe` that is improperly using this extension, and causing it to crash.

If @winzig also has the `stripe.vscode-stripe` extension installed, and especially if the Crashpad handler stops running when deactivating the extension, then the issue is maybe on the side of the extension and we can open an issue in that repo instead. But if the OP doesn't have the Stripe extension, then it's more likely that the issue is in `ms-dotnettools.vscode-dotnet-runtime`.

At the very least, based on the issue in VS Code's repo, it seems that the stacktrace found in the dump files point to `ms-dotnettools.vscode-dotnet-runtime` specifically.

As for me, for now, I'll disable Stripe's extension, now that I know how to avoid the issue completely!

---

So, as I said, I ran the `.NET Install Tool: Report an issue with the .NET Install Tool for Extension Authors` on the window causing the problem (before disabling Stripe's extension).

Given that it is empty, GitHub doesn't let me upload it, though I doubt it would have been helpful in that state.

The name of the empty file is `DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1625083059683.txt`.

**Comment by winzig** [comment] 2021-06-30 20:19
I also checked for any other files named `DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-*` and there are 11 of them, but they are also zero bytes.

**Comment by winzig** [comment] 2021-06-30 20:19
Interesting, I also have the `stripe` extension installed...

**Comment by winzig** [comment] 2021-06-30 20:23
cc @gracegoo-stripe @vcheung-stripe are you folks aware of any issues with `vscode-stripe`?

**Comment by sfoslund** [comment] 2021-06-30 20:29
I suspect that this is an issue with the extension that is leveraging the vscode-dotnet-runtime extension (in this case, it sounds like that's vscode-stripe). The vscode-dotnet-runtime extension simply installs the .NET runtime onto the machine but never runs it, the leveraging extension can do whatever they want with the runtime from there. Based on the error message it looks like this is an issue with how the runtime is being used, which is unrelated to the installation this extension manages. 

As a result, I'm going to transfer this issue to the vscode-stripe repo, feel free to move it back if you find a installation specific issue, thanks!

**Comment by sfoslund** [comment] 2021-06-30 20:30
This issue was moved to stripe/vscode-stripe#292

**Closed by sfoslund** 2021-06-30 20:30 UTC

**Comment by winzig** [comment] 2021-06-30 21:15
@sfoslund Thanks for the help with this. BTW, do you think it considered to be a separate issue that chrome_crashpad_handler can sort of silently run amok like it was for us? And if so, would that be reported here or somewhere else?

**Comment by sfoslund** [comment] 2021-06-30 21:32
No problem! I'm not sure, I would ask the vscode-stripe folks about whether it might be related or if they know where to file an issue, but it does not sound like it could be related to this extension.
