### ISSUE TITLE
Architecture mismatch between VSCode and Install-Scripts for downloaded Runtime/SDK

### ISSUE THREAD

**Issue by 4ColorDesign** [dotnet/vscode-dotnet-runtime#1338] opened 2023-08-28 11:49 UTC
# Describe the bug
  Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
[Error - 4:13:01 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
    at t.DotnetRuntimeExtensionResolver.<anonymous> (c:\Users\atulm\.vscode\extensions\ms-dotnettools.csharp-2.0.413-win32-x64\dist\extension.js:2:1382303)
    at Generator.next (<anonymous>)
    at s (c:\Users\atulm\.vscode\extensions\ms-dotnettools.csharp-2.0.413-win32-x64\dist\extension.js:2:1380683)

  
  
  ## **Please attach log file(s) here if you have any:**
  >❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement
  
  
  
  If you came here from VS Code, the log file location should be copied to the clipboard.
  
  ## Other Info:
  Errors the extension may have encountered have likely been added to your terminal or VS Code windows. Please paste it/them here and describe what happened and the problem you are facing.
  
  **Reproduction Steps**
  
  
  **Expected behavior**
  
  
  **Exceptions & Errors (if any)**
  
  
  **Further technical details**
  - Your VSCode Version
  
  - The version of the extension that's on your machine
  
  - Your operating system details

**Comment by ReyZRX** [comment] 2023-09-01 19:33
Howdy. I have a similar err on which I spent the day futzing with after deciding to try C# extension on VS Code. Started w/Net SDK 7 and uninstalled that and C#, C# dev kit and problem still happens. Will now go back to C# 2010 Express as all I wanted to do was read the Beginning C# 2008 Objects book to get round to reading on OOP..

Been retired for 5 yrs now and now this...

Thanks for any assistance you/others may have on fixing this,

Rey

[CSharp_DevKit_err.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/12501060/CSharp_DevKit_err.txt)

**Comment by dibarbet** [comment] 2023-09-01 20:05
@ReyZRX 

Thanks for the logs, they're useful.  It looks like you have the ia32 version of the extension, but an x64 version of dotnet.  Are you by chance using the ia32 version of vscode?

You can check by going to Help -> About, under OS it will say Windows_NT ia32 if you have the 32bit version of vscode.
If so, I'd suggest switching to the x64 version of vscode and that should resolve your issue.

### Bug details

We still have a bug here though, because ideally even if you have the ia32 version of the extension, the runtime download would be able to acquire the right dotnet.
@nagilson I've been able to reproduce this issue.  Basically if you install the ia32 version of vscode, it will always download the ia32 version of the extension (no matter the underlying platform).  If the dotnet on the path is x64, we'll show an error (platform mismatch) and try to download using the runtime extension.  However the runtime extension also downloads x64:
```
c:\Users\WDAGUtilityAccount\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe --info

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.10 [C:\Users\WDAGUtilityAccount\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\shared\Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info
```

**Comment by nagilson** [comment] 2023-09-06 21:12
@dibarbet For the runtime extension, the architecture of VS Code itself does not have much impact on the architecture of the .NET Runtime it installs (the install script is what determines the architecture and it does that based on the shell it's executing from.)

This seems like a bug in the install script.
We could definitely make it install whichever architecture comes out of `os.arch()` in node.

May you share the output of the following:

If on linux, what is the output of `uname -m` and if on Windows on pwsh, whats the output of `ls env:PROCESSOR_ARCHITEW6432` `((Get-CimInstance -ClassName CIM_OperatingSystem).OSArchitecture)` and `ls env:PROCESSOR_ARCHITECTURE`?

That's what the runtime will use (aka what the install script uses, so the runtime just does that). Perhaps there is a red herring in there making the install script think you're on x64, or the shell vscode is running on is actually x64 even though vscode is ia32?

**Comment by dibarbet** [comment] 2023-09-06 21:26
> This seems like a bug in the install script though we would hopefully be able to account for it better.
We could definitely make the extension install whichever architecture comes out of os.arch() in node as a fix from our end though. This is what the global SDK extension does.

Is it possible to detect the arch to install based on the dll / exe we pass to you (as long as it is also compatible with the OS)?

> or the shell vscode is running on is actually an x64 terminal even though vscode is ia32?

I believe this is the case (O# uses this code to determine the architecture, and it downloads x64 even if the extension installed is ia32)
https://github.com/dotnet/vscode-csharp/blob/main/src/shared/platform.ts#L165
It outputs `Platform: win32, x86_64` even though I installed the ia32 version of vscode (and the extension).

We've also been wondering if we should just ship x64 and ia32 in the same vsix and choose at runtime, but that bloats vsix size a lot.

**Comment by nagilson** [comment] 2023-09-06 21:43
> Is it possible to detect the arch to install based on the dll / exe we pass to you (as long as it is also compatible with the OS)?

I'm not quite sure what you mean, though I'm sorry as I meant `os.platform()` not `os.arch()`. This seems like a more reliable option IMO as os.arch() should actually return the architecture Node is running on, which is theoretically the same as VS Code. At least it will not return x64 due to the shell being an x64 process. 

As for which dll/exe ... are you referring to if a custom dotnet path is set? Because when a call to the API is made there is no exe/dll exchange and that is what determines the architecture of dotnet to insall. Are you shipping C# / CDK with a runtime and then setting a custom path?

**Comment by nagilson** [comment] 2023-09-06 21:48
> Is it possible to detect the arch to install based on the dll / exe we pass to you (as long as it is also compatible with the OS)?

Also, if you are using a custom path with your own runtime, all the extension does is accept what you told it to use and return the path to it that you gave.. there is no logic for it to do anything with that information as it doesn't really do.. well, much of anything at all at that point

**Comment by dibarbet** [comment] 2023-09-06 21:52
> I'm not quite sure what you mean:

So we pass you our actual server exe / dll here when we acquire the runtime - https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/dotnetRuntimeExtensionResolver.ts#L117 .  I was wondering if it were possible to look at that exe we give you and download the appropriate architecture based on what architecture that exe was built for.  That may not be possible, but was wondering if what was an option.

**Comment by dibarbet** [comment] 2023-09-06 21:54
We can also figure out what architecture the exe was built for using the extension architecture, and then tell you which one to download based on that potentially.

> At least it will not return x64 due to the shell being an x64 process. This whole blurb is if you are calling into the API to have the runtime extension install a runtime for you.

This might work, if node gives you ia32 when vscode is running as ia32.

**Comment by nagilson** [comment] 2023-09-06 22:06
Oh interesting, I did not know that you pass the Roslyn Language Sever to us. That's a really smart idea, I like it. My Roslyn knowledge is rather lacking 😄 But I talked to @baronfel about it and sadly, that's not a super feasible option. There's likely a lot of OS & platform-specific code we would need to write to read specific parts of the binary's folder.

**Comment by nagilson** [comment] 2023-09-06 22:09
Also I like the idea of us adding an architecture flag to the extension. We'd need to do that eventually if customers wanted to, for some reason, run dotnet in an architecture that's different from VS Code.

But I think the most straight-forward thing we can do is try to rely on the node architecture and tell the install script to use that instead. I'm glad to give that a go... do you have an easy repro if I gave you a patch to see if it worked? 

Thanks!

**Comment by dibarbet** [comment] 2023-09-06 22:18
> I'm glad to give that a go... do you have an easy repro if I gave you a patch to see if it worked?

Yeah I can.  If you'd find it faster it should be easy for you to repro as well in a windows sandbox.  The absolute simplest way there is:
1.  Download and install x64 .net7 SDK
2. Download and install ia32 vscode - pick the x86 one here https://code.visualstudio.com/download
3.  Install the C# extension
4.  Create a new console app and open in vscode

**Comment by nagilson** [comment] 2023-09-06 22:26
Awesome, thanks :) I'll take a look into this.

**Comment by ReyZRX** [comment] 2023-09-25 17:41
David: apologies for lateness of reply.
Did as you suggested and it was a 32bit install - now 64.
Continued w/same problem and resolved by removing the path entry from the
environmental variables for user from what I recall at this date.
Interestingly, the other box - also w/a 32 install that received the same
treatment - did not need its environmental variable PATH entry changed...

Thanks again,
Rey

**Comment by baronfel** [comment] 2023-09-25 21:10
Closing now that the associated PR is merged - v 1.8.0 will contain this fix.

**Closed by baronfel** 2023-09-25 21:10 UTC
Labels: install scripts

**Comment by amiru3f** [comment] 2023-10-14 12:54
Hello,
I see something like this problem.
Versions:
.NET Runtime Install Tool V1.8.1
Dev Kit v0.5.150
Intellicode v0.1.26

Please find the corresponding logs attached:

``` Stacktrace
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...

[stdout] {"pipeName":"/var/folders/d2/tlltgdnd27jdgk6ww4cvqfk40000gn/T/d1eaab4e-73ab-4321-b7cf-7207e87130d1.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Error - 2:48:46 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed

[Info  - 2:48:46 PM] Connection to server got closed. Server will restart.
true

[Error - 2:48:46 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stderr] Unhandled exception: [stderr] Newtonsoft.Json.JsonSerializationException: Error writing JSON RPC Message: TypeLoadException: Could not load type 'System.Text.Json.Serialization.JsonRequiredAttribute' from assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
 ---> System.TypeLoadException: Could not load type 'System.Text.Json.Serialization.JsonRequiredAttribute' from assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetSerializableMembers(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer, JsonRpcMessage message)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.WriteAsync(JsonRpcMessage content, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.SendAsync(JsonRpcMessage message, CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.HandleRpcAsync(JsonRpcMessage rpc)
   at Microsoft.CodeAnalysis.LanguageServer.LanguageServer.LanguageServerHost.WaitForExitAsync() in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/LanguageServer/LanguageServerHost.cs:line 59
   at Program.<<Main>$>g__RunAsync|0_0(ServerConfiguration serverConfiguration, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs:line 126
   at Program.<<Main>$>g__RunAsync|0_0(ServerConfiguration serverConfiguration, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Program.cs:line 134
   at System.CommandLine.CliCommand.<>c__DisplayClass32_0.<<SetAction>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCliAction.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
Language server process exited with 1
```

**Comment by amiru3f** [comment] 2023-10-14 13:12
Also cleaned up the folders and reinstalled them using `vs-code` recommendation. Did not work.

**Comment by baronfel** [comment] 2023-10-14 13:25
That looks like an error that's coming directly from the C# extensions, can you raise this at https://github.com/dotnet/vscode-csharp?

**Comment by amiru3f** [comment] 2023-10-14 13:49
@baronfel  thanks for the quick reply, Done: https://github.com/dotnet/vscode-csharp/issues/6545
