### ISSUE TITLE
The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/vscode-dotnet-runtime#1103] opened 2023-07-19 11:15 UTC
**Repro steps:**

1. `dotnet new console` -> open the created project in VSCode

**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" argument must be of type string. Received an instance of Object
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at normalizeSpawnArguments (node:child_process:527:3)
	at Object.spawnSync (node:child_process:825:8)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095661
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095584
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37962
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36621
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:36366)
	at t.callWithErrorHandling (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:37910)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095578
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1092018
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1091763)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/dist/extension.js:2:1095512
	at e.$vL.h (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:64085)
	at e.$vL.g (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:63073)
	at e.$vL.executeCommand (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:62973)
	at Object.executeCommand (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:20971)
	at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
	at Generator.next (<anonymous>)
	at s (/home/anonymous/.vscode/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)

The file `/home/vincent/.config/Code/logs/20230719T131114/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689765076633.txt` is empty:

![grafik](https://github.com/dotnet/vscode-dotnet-runtime/assets/20972129/68f79499-46fb-454e-b8db-bcc796a8a76e)

❯ dotnet --info

```
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Laufzeitumgebung:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /home/vincent/Dokumente/Software/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: x64
  Commit:       4b0550942d

.NET SDKs installed:
  5.0.408 [/home/vincent/Dokumente/Software/dotnet/sdk]
  6.0.404 [/home/vincent/Dokumente/Software/dotnet/sdk]
  7.0.101 [/home/vincent/Dokumente/Software/dotnet/sdk]
  7.0.302 [/home/vincent/Dokumente/Software/dotnet/sdk]
  7.0.305 [/home/vincent/Dokumente/Software/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/home/vincent/Dokumente/Software/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/vincent/Dokumente/Software/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by Apollo3zehn** [comment] 2023-07-19 11:16
Interestingly the extension seems to work - at least the test explorer shows tests and I can run them.

**Comment by baronfel** [comment] 2023-07-19 12:01
Closing as a duplicate of #1007, in the meantime you can downgrade the c# extension to 2.0.248 to not trigger the error.

**Closed by baronfel** 2023-07-19 12:01 UTC
