### ISSUE TITLE
.NET Runtime installer is failing

### ISSUE THREAD

**Issue by aidedinertial** [dotnet/vscode-dotnet-runtime#537] opened 2022-07-22 15:30 UTC
**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.7" -Version 6.0.7 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.7" -Version 6.0.7 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

    /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/extension.js:2:13750

**Comment by nagilson** [comment] 2022-10-14 23:00
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 23:00 UTC
