### ISSUE TITLE
.NET runtime error

### ISSUE THREAD

**Issue by joeboadiDev** [dotnet/vscode-dotnet-runtime#1031] opened 2023-07-13 13:10 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/joeboadiorion/.config/Code/logs/20230713T123746/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689252011651.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment] 2023-07-17 14:40
This is likely a duplicate of #1007.

**Closed by baronfel** 2023-07-17 14:40 UTC
