### ISSUE TITLE
Error after starting vscode

### ISSUE THREAD

**Issue by TymianekPL** [dotnet/vscode-dotnet-runtime#546] opened 2022-07-28 09:15 UTC
**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server-insiders/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.7" -Version 6.0.7 -Runtime dotnet
/home/anonymous/.vscode-server-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server-insiders/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.7" -Version 6.0.7 -Runtime dotnet
/home/anonymous/.vscode-server-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

    at /home/anonymous/.vscode-server-insiders/extensions/vscode-dotnet-runtime-library/dist/Acquisition/DotnetCoreAcquisitionWorker.js:89:27

**Comment by hansmbakker** [comment] 2022-08-26 09:05
This is related to https://github.com/dotnet/vscode-dotnet-runtime/issues/159

**Comment by nagilson** [comment] 2022-10-14 22:53
Closing as dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 -- thanks!

**Closed by nagilson** 2022-10-14 22:53 UTC
