### ISSUE TITLE
Mac Visual Studio Code "Error Acquiring .NET"

### ISSUE THREAD

**Issue by mokeweb** [dotnet/vscode-dotnet-runtime#348] opened 2021-11-19 14:15 UTC
Please note that the requested log file was empty

I am trying to get bicep working in VS Code on an M1 Macbook Air running Monterrey.  I get the following error:

An error occurred while installing .NET (5.0): .NET Acquisition Failed: Installation failed: Error: Command failed: "/Users/jamesclarke/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.4.0/dist/install scripts/dotnet-install.sh" -InstallDir "/Users/jamesclarke/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.12" -Version 5.0.12 -Runtime dotnet dotnet_install: Error: Could not find `.NET Core Runtime` with version = 5.0.12 dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

I have tried manually installing .NET 5.0 and 6.0.  I have the .NET extension.  Nothing I am doing can get it to work.  I tried to follow this as well with no success:

https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md

I followed the Manually installing .NET part).  It is very vague about what to actually do as it just says to update settings.  I have put it into settings.json for the VSCode .Net Extension.

**Comment by sfoslund** [comment] 2021-11-19 17:03
@mokeweb the problem is that .NET 5 and lower are not supported on M1/ arm64 devices. You can try installing .NET 6 and pointing to it using the workaround provided here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#mac, but otherwise it is up to the extension that is requesting .NET to update to .NET 6. Do you happen to know which extension you're using requires .NET 5?

**Comment by mokeweb** [comment] 2021-11-19 17:09
Hi, thanks for your response.  I did try that along with installing .NET 6.  I mentioned above that it is not clear where to put that information, all the page says is to update settings but it does not say where these settings are or how to edit them.

I am trying to use the Bicep Extension.

**Comment by sfoslund** [comment] 2021-11-19 17:18
@mokeweb sorry, I missed that part. You can get to the settings with ctrl-shift-p, then search settings, and choose `Preferences: Open settings (JSON)`. That will open a json file that you can copy the json snippet from our docs into. 

Note that this workaround may not work anyways, just depending on how the bicep extension is implemented. Looking at [their repo](https://github.com/Azure/bicep/commits/main/src/vscode-bicep) I notice that they seem to have updated to .NET 6 this week, so once that update is released this should be all fixed up. @majastrz did the change, when should we expect to see it released?

**Comment by mokeweb** [comment] 2021-11-19 17:36
Thank you Sarah, appreciate you being so helpful.  I have tried above but am getting the same error.  I will wait for the next version and in the mean time use VSCode on my Win 10 machine instead.

**Comment by sfoslund** [comment] 2021-11-19 17:46
Sounds good, I'm going to close this issue as the fix is on Bicep's side, but feel free to reopen if you have further questions.

**Closed by sfoslund** 2021-11-19 17:46 UTC

**Comment by mokeweb** [comment] 2021-11-19 23:32
Thanks Sarah
