### ISSUE TITLE
.NET Install Tool for Extension Authors  v1.6.0  - The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by arielveron** [dotnet/vscode-dotnet-runtime#1011] opened 2023-07-12 22:10 UTC
Download of DotNet runtime 7.0.9 was interrupted by VSCode when a restart to reload the newest extensions was performed.
Since then, an error at the bottom bar shows "Error acquiring .NET!"

Restarting VSCode Insiders or reinstalling the extensions:

C# - v2.0.249 pre-release
C# Dev kit - v0.3.2 pre-release
.NET Install Tool for Extension Authors - v1.6.0

doesn't make the error go away.

**Repro steps:**
1.

**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at normalizeSpawnArguments (node:child_process:527:3)
    at Object.spawnSync (node:child_process:825:8)
    at /home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:153:31
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49
    at new Promise (<anonymous>)
    at n (/home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49)
    at callback (/home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:147:49)
    at next (/home/anonymous/.vscode-insiders/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:54:34)
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode-insiders/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anonymous/.vscode-insiders/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:4:12)
    at callWithErrorHandling (/home/anonymous/.vscode-insiders/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:52:12)
    at /home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:147:15
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49
    at new Promise (<anonymous>)
    at n (/home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49)
    at /home/anonymous/.vscode-insiders/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:146:196
    at c.h (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:63280)
    at c.g (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:62275)
    at c.executeCommand (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:62182)
    at Object.executeCommand (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:20976)
    at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.vscode-insiders/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
    at Generator.next (<anonymous>)
    at s (/home/anonymous/.vscode-insiders/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)

**Comment by Shinjoku** [comment] 2023-07-12 22:15
Same here

**Comment by vlariono** [comment] 2023-07-13 18:35
Duplicate of #1007

**Comment by baronfel** [comment] 2023-07-17 14:10
Closing as duplicate

**Closed by baronfel** 2023-07-17 14:10 UTC
