### ISSUE TITLE
Failed to install .Net runtime when opening a .bicep file

### ISSUE THREAD

**Issue by aurasolutions** [dotnet/vscode-dotnet-runtime#347] opened 2021-11-19 11:24 UTC
When attaching to a WSL Remote folder using VS Code and opening a .bicep file, the app displays an error that it cannot load the .net runtime v5.0

Error: 
.NET Acquisition Failed: Installation failed: Error: Command failed: "/home/scott/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.4.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/scott/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/5.0.12" -Version 5.0.12 -Runtime dotnet
/home/scott/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.4.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

The log file located at /home/scott/.vscode-server/data/logs/20211119T061743/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1637320672304.txt. 

was an empty file, so I have no logs with this issue

Restarting VSCode and reopening the WSL remote fixes the issue until I open a folder in Windows (non-wsl remote), then the error returns

**Comment by nagilson** [comment] 2022-10-14 23:15
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 23:15 UTC
