### ISSUE TITLE
Error reported when viewing ARM template json file

### ISSUE THREAD

**Issue by GeorgeJoy** [dotnet/vscode-dotnet-runtime#160] opened 2021-01-17 08:28 UTC
> dotnet-install.ps1:25 char:3
> + if [ -t 1 ] && command -v tput > /dev/null; then

[DotNetAcquisition1610754615908.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5825741/DotNetAcquisition1610754615908.txt)

**Comment by nagilson** [comment] 2022-06-27 21:22
Seems to be a duplicate of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 which we are in the middle of investigating. Thanks for reporting it. If you have any other concerns or think this is not a duplicate, feel free to re-open the issue with us.

**Closed by nagilson** 2022-06-27 21:22 UTC
Labels: bug
