### ISSUE TITLE
Cancelled Installation of .NET 8.0.10. The requested and or resolved version is invalid.

### ISSUE THREAD

**Issue by rhys-vdw** [dotnet/vscode-dotnet-runtime#2017] opened 2024-11-13 01:11 UTC
### Describe the bug.

I see this when opening VSCode (project has not changed since yesterday)

![Image](https://github.com/user-attachments/assets/f3619142-c374-422f-b6a6-4bd1415c9579)

```
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.
```

### Please attach log file(s) here if you have any.

[20241113T115848.zip](https://github.com/user-attachments/files/17724621/20241113T115848.zip)
The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Open project in VSCode, observe errors

### Expected Behavior

I don't get errors.

### Exceptions & Errors (if any)

(as above)

### .NET Install Tool Version

v2.2.2

### Your operating system? Please provide more detail, such as the version and or distro above.

Windows

### VS Code Version

1.95.2

**Comment by Leonardo-Ferreira** [comment] 2024-11-13 01:39
same here... extra details: im on Mac Sonoma 14.7

**Comment by Ed-Gilmour** [comment] 2024-11-13 01:39
I'm getting these errors as well
`Cancelled Installation of .NET 8.0.10.
The requested and or resolved version is invalid.`

**Comment by magicjar** [comment] 2024-11-13 01:44
For a temporary workaround, you can install the latest .NET SDK manually (8.0.11).
This solved the issue for me.

**Comment by Matt-Crow** [comment] 2024-11-13 02:12
I am encountering the same problem.
My operating system is Mac OS Sequoia v15.1 .
This error began around when the `.NET Install Tool`, `C#`, and `C# Dev Kit` VSCode extensions by Microsoft updated, so one of those might have an issue.

Hope this helps!

**Comment by SWeetJellyStudio** [comment] 2024-11-13 04:59
I encountered same issue.
Downgrading the C# extension to version 2.50.27, instead of the latest 2.55.28, resolved the issue.

**Comment by mccaffers** [comment] 2024-11-13 08:54
Setting dotnetAcquisitionExtension.existingDotnetPath helped:
![Image](https://github.com/user-attachments/assets/83f9021f-52bc-4e4f-a33a-4dfa9aa3c551)

```
   "dotnetAcquisitionExtension.existingDotnetPath": [
        {"extensionId": "msazurermtools.azurerm-vscode-tools", "path": "/usr/local/share/dotnet/dotnet"}
    ]
```

**Comment by kmnunley** [comment] 2024-11-13 16:09
Duplicate of #2012

**Comment by nagilson** [comment] 2024-11-13 17:29
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.

**Closed by nagilson** 2024-11-13 17:29 UTC
Labels: untriaged
