### ISSUE TITLE
Error when starting VSCode 

### ISSUE THREAD

**Issue by wgrs** [dotnet/vscode-dotnet-runtime#1023] opened 2023-07-13 09:13 UTC
After installing the C# Dev kit, I started getting an error when starting VSCode. 

**Extension Version:** 1.0.0
**Error Message:** The "file" argument must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:121:11)
    at normalizeSpawnArguments (node:child_process:527:3)
    at Object.spawnSync (node:child_process:825:8)
    at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:153:31
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49
    at new Promise (<anonymous>)
    at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49)
    at callback (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:147:49)
    at next (/home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:54:34)
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:4:12)
    at callWithErrorHandling (/home/anonymous/.vscode/extensions/vscode-dotnet-runtime-library/dist/Utils/ErrorHandler.js:52:12)
    at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:147:15
    at Generator.next (<anonymous>)
    at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49
    at new Promise (<anonymous>)
    at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/DotnetCoreAcquistionId.ts:6:49)
    at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.6.0/src/extension.ts:146:196
    at e.$vL.h (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:64085)
    at e.$vL.g (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:63073)
    at e.$vL.executeCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:62973)
    at Object.executeCommand (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:20971)
    at t.DotnetRuntimeExtensionResolver.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1010140)
    at Generator.next (<anonymous>)
    at s (/home/anonymous/.vscode/extensions/ms-dotnettools.csharp-2.0.249-linux-x64/dist/extension.js:2:1008463)

**Comment by MathanGeurtsen** [comment] 2023-07-13 10:25
I got the same message, also with the C# Dev kit. The problem seems to be the upgrade of the C# extension to the pre release version. if I downgrade the C# extension back to the Release version the error disappears, moving the C# extension to pre release without the dev kit also shows this error. I'm on ubuntu 20 LTS.

**Comment by baronfel** [comment] 2023-07-17 14:16
Closing as duplicate of #1007

**Closed by baronfel** 2023-07-17 14:16 UTC
