### ISSUE TITLE
Got this error when via VS Code when updating Azure ARm Template extension

### ISSUE THREAD

**Issue by fitzgeraldsteele** [dotnet/vscode-dotnet-runtime#98] opened 2020-06-16 15:35 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1.

**Extension Version:** 0.1.2
**Error Message:** Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.5" -Runtime dotnet -Version 3.1.5
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: Syntax error: newline unexpected

**Error Stack:** Error: Dotnet Core Acquisition Failed: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/3.1.5" -Runtime dotnet -Version 3.1.5
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: 7: /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/extension.js:211:111243
Please attach the log file located at /home/fisteele/.vscode-server/data/logs/20200616T083335/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition1592321647042.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by sfoslund** [comment] 2020-06-16 16:30
@fitzgeraldsteele thanks for filing an issue. It looks like this is an issue with running the install scripts, do you mind giving us some more debugging information? If you could provide the contents of the install script (`/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-0.1.2/dist/install scripts/dotnet-install.sh`) and the log file (`/home/anonymous/.vscode-server/data/logs/20200616T083335/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition1592321647042.txt`), that would be very helpful, thanks!

**Comment by dnchance** [comment] 2020-08-20 19:53
Getting the same error but on Windows.
Contents of Install Script:

[dotnet-install.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5105163/dotnet-install.txt)

log file:
[DotNetAcquisition1597952140705.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/5105171/DotNetAcquisition1597952140705.txt)

**Comment by sfoslund** [comment] 2020-08-20 22:19
> Import-Module : The specified module 'C:\scratch\git\Modules\QT.SystemsINF.Core\QT.SystemsINF.Core.psm1' was not 
loaded because no valid module file was found in any module directory.
At C:\Users\dchance\ShareFile\Personal Folders\Documents\WindowsPowerShell\profile.ps1:11 char:1

@dnchance It looks like an import that was specified in your powershell profile failed.

**Comment by sfoslund** [comment] 2020-10-01 15:57
This looks like a duplicate of https://github.com/dotnet/vscode-dotnet-runtime/issues/121, which will be fixed with the next release. Please feel free to reopen this issue if it still repros after that, thanks!

**Closed by sfoslund** 2020-10-01 15:57 UTC
Labels: bug, install scripts
