### ISSUE TITLE
.NET Acquisition Failed for .NET 6

### ISSUE THREAD

**Issue by shaunm-msft** [dotnet/vscode-dotnet-runtime#456] opened 2022-05-11 15:36 UTC
The log file located at c:\Users\shaunm\AppData\Roaming\Code - Insiders\logs\20220511T081602\exthost1\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1652282167021.txt is empty.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Repro steps:**

1. I started code-insiders and it updated to the May release.

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Missing file specification after redirection operator.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:3
+ if [ -t 1 ] && command -v tput > /dev/null; then
+   ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:5
+ if [ -t 1 ] && command -v tput > /dev/null; then
+     ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:25 char:13
+ if [ -t 1 ] && command -v tput > /dev/null; then
+             ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:7
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+       ~
Missing '(' after 'if' in if statement.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:9
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+         ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:26
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                          ~~
The token '&&' is not a valid statement separator in this version.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:28 char:30
+     if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
+                              ~
Missing type name after '['.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:42 char:13
+ say_warning() {
+             ~
An expression was expected after '('.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
Missing file specification after redirection operator.
At C:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1:43 char:72
+ ... printf "%b\n" "${yellow:-}dotnet_install: Warning: $1${normal:-}" >&3
+                                                                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingOpenParenthesisInIfStatement
 

	at c:\Users\anonymous\.vscode-insiders\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\extension.js:2:13750

**Comment by nagilson** [comment] 2022-06-27 17:27
Sorry to hear you're experiencing this issue. Seems to be a duplicate of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 which we are in the middle of investigating. Thanks for reporting it. If you have any other concerns or think this is not a duplicate, feel free to re-open the issue with us.

**Closed by nagilson** 2022-06-27 17:27 UTC
