### ISSUE TITLE
Cancelled installation of .NET 8.0.10.

### ISSUE THREAD

**Issue by hugoalmeida-pt** [dotnet/vscode-dotnet-runtime#2026] opened 2024-11-13 09:35 UTC
### Describe the bug.

![Image](https://github.com/user-attachments/assets/2ca1af42-7eb2-4ad4-bf02-036598f2236d)

### Please attach log file(s) here if you have any.

The log file location should be copied to your clipboard if you came from VS Code.

### Reproduction Steps

Just open a dotnet project

### Expected Behavior

Should run everything flawlessly.

### .NET Install Tool Version

8.0.10

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.95.2

**Comment by rafael-weilharter** [comment] 2024-11-13 09:52
I'm getting the same issue today after restarting VSCode.

**Comment by Novack** [comment] 2024-11-13 10:54
Duplicate of #2022

**Comment by peyronth** [comment] 2024-11-13 15:04
Here is a temporary fix : https://github.com/dotnet/vscode-dotnet-runtime/issues/2022#issuecomment-2472980072

**Comment by nagilson** [comment] 2024-11-13 17:28
Thanks for your resolution everyone. I found the issue with the most comments and proposed a resolution here.
-> https://github.com/dotnet/vscode-dotnet-runtime/issues/2021 <- You can read how to resolve it, etc, here.

I'm gonna close this issue since this is a duplicate issue.

**Closed by nagilson** 2024-11-13 17:28 UTC
Labels: untriaged
