### ISSUE TITLE
olimboy1

### ISSUE THREAD

**Issue by olimboy1** [dotnet/vscode-dotnet-runtime#1027] opened 2023-07-13 12:05 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\Олимбай\AppData\Roaming\Code\logs\20230713T163317\window1\exthost\ms-dotnettools.vscode-dotnet-sdk\DotNetAcquisition-ms-dotnettools.vscode-dotnet-sdk-1689249846368.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment] 2023-07-17 14:40
This is likely a duplicate of #1007.

**Closed by baronfel** 2023-07-17 14:40 UTC
