### ISSUE TITLE
Erro acquring .NET on linux

### ISSUE THREAD

**Issue by yanivsag** [dotnet/vscode-dotnet-runtime#1068] opened 2023-07-16 17:24 UTC
trying to run the c# dev kit on linux. 
failing with "Error acquiring .NET!".
also happens with remote connection from windows to linux.
solution is not getting loaded as a result and tests couldn't be executed

The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/yaniv/.config/Code/logs/20230716T201343/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689527846677.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment] 2023-07-17 14:21
Closing as duplicate of #1007

**Closed by baronfel** 2023-07-17 14:21 UTC
