### ISSUE TITLE
Error when attempting to install .Net from the Bicep VSCode Extension

### ISSUE THREAD

**Issue by BenResTech** [dotnet/vscode-dotnet-runtime#629] opened 2022-10-13 14:42 UTC
**Repro steps:**

1. Install the Bicep and .NET Install Tool extensions
2. On the Bicep extension's launch page, click the 'Create Bicep file' button

```
**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\benjamin.allen\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\benjamin.allen\.vscode\extensions\ms-dotnetto ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Cannot set property. Property setting is supported only on core types in this language mode.
At line:1 char:5
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointMa ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage
 
C:\Users\benjamin.allen\.vscode\extensions\ms-dotnettools.vscode-dotnet-runtime-1.5.0\dist\install 
scripts\dotnet-install.ps1 : Cannot invoke method. Method invocation is supported only on core types in this language 
mode.
At line:1 char:136
+ ... e]::Tls12 ; & 'c:\Users\benjamin.allen\.vscode\extensions\ms-dotnetto ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [dotnet-install.ps1], RuntimeException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage,dotnet-install.ps1
 

    at c:\Users\benjamin.allen\.vscode\extensions\vscode-dotnet-runtime-library\dist\Acquisition\DotnetCoreAcquisitionWorker.js:89:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

[DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1665671549832.txt](https://github.com/dotnet/vscode-dotnet-runtime/files/9777788/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1665671549832.txt)

**Comment by nagilson** [comment] 2022-10-14 21:33
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 21:33 UTC
