### ISSUE TITLE
can't run .net in my ubuntu 23.10

### ISSUE THREAD

**Issue by khaimed** [dotnet/vscode-dotnet-runtime#1073] opened 2023-07-16 22:07 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/khaimed/.config/Code/logs/20230716T230303/window6/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689545007461.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by baronfel** [comment] 2023-07-17 14:21
Closing as duplicate of #1007

**Closed by baronfel** 2023-07-17 14:21 UTC
