### ISSUE TITLE
An error occurred while installing .NET (6.0): .NET Acquisition

### ISSUE THREAD

**Issue by EdgarGrimbergNOV** [dotnet/vscode-dotnet-runtime#523] opened 2022-07-11 07:05 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

**Repro steps:**

1. I just opened VSCode remote over SSH on a freshly installed Ubuntu 22.04 LTS

**Extension Version:** 1.0.0
**Error Message:** .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.6" -Version 6.0.6 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

**Error Stack:** Error: .NET Acquisition Failed: Installation failed: Error: Command failed: "/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh" -InstallDir "/home/anonymous/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/6.0.6" -Version 6.0.6 -Runtime dotnet
/home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/install scripts/dotnet-install.sh: 7: Syntax error: newline unexpected

	at /home/anonymous/.vscode-server/extensions/ms-dotnettools.vscode-dotnet-runtime-1.5.0/dist/extension.js:2:13750

Please attach the log file located at /home/edgar/.vscode-server/data/logs/20220711T085916/exthost1/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1657522759000.txt. Note that this file may contain personal data.

_The log file is empty_

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by MeetSon1** [comment] 2022-09-18 12:59
same issue

**Comment by nagilson** [comment] 2022-10-14 23:01
Heya, thanks for the detailed issue. This is a dupe of https://github.com/dotnet/vscode-dotnet-runtime/issues/159 and will be fixed in the 1.6.1 release. Closing, but feel free to ask any concerns over there.

**Closed by nagilson** 2022-10-14 23:01 UTC
