### ISSUE TITLE
Error! The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by elvesbd** [dotnet/vscode-dotnet-runtime#1008] opened 2023-07-12 19:35 UTC
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at /home/ebd/.config/Code/logs/20230712T161715/window1/exthost/ms-dotnettools.vscode-dotnet-runtime/DotNetAcquisition-ms-dotnettools.vscode-dotnet-runtime-1689190441889.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by incomingstick** [comment] 2023-07-12 19:43
this is a duplicate of #1007 I think

**Closed** 2023-07-17 14:09 UTC
