### ISSUE TITLE
Reported issue: The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by anstropleuton** [dotnet/vscode-dotnet-runtime#1033] opened 2023-07-13 14:05 UTC
I am running Arch Linux and downloaded vs code from the unofficial repositories.
I have downloaded and installed the C# extension from the [official website](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) instead of from the extensions section.
Looks like there is no Repro steps, here is what I did:
install `code` and `dotnet-sdk` from Arch Linux package manager `pacman`:
```
sudo pacman -Sy code dotnet-sdk
```
Download extension file from the website https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
And install the extension the extension from "Install from VSIX" option.
Here is the issue found:

```
The issue text was copied to the clipboard.

**Repro steps:**

1.

**Extension Version:** 1.0.0
**Error Message:** The "file" arguanonymousnt must be of type string. Received an instance of Object
**Error Stack:** TypeError: The "file" arguanonymousnt must be of type string. Received an instance of Object
	at new NodeError (node:internal/errors:387:5)
	at validateString (node:internal/validators:121:11)
	at normalizeSpawnArguanonymousnts (node:child_process:527:3)
	at Object.spawnSync (node:child_process:810:8)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:8409
	at Generator.next (<anonymous>)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:4766
	at new Promise (<anonymous>)
	at n (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:4511)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:8332
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:46946
	at Generator.next (<anonymous>)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:45605
	at new Promise (<anonymous>)
	at n (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:45350)
	at t.callWithErrorHandling (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:46894)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:8326
	at Generator.next (<anonymous>)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:4766
	at new Promise (<anonymous>)
	at n (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:4511)
	at /hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtianonymous-1.6.0-universal/dist/extension.js:2:8260
	at e.ExtHostCommands.h (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:99:130664)
	at e.ExtHostCommands.g (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:99:129554)
	at e.ExtHostCommands.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:99:129454)
	at Object.executeCommand (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:117:24230)
	at t.DotnetRuntianonymousExtensionResolver.<anonymous> (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.csharp-2.0.249/dist/extension.js:2:1010140)
	at Generator.next (<anonymous>)
	at s (/hoanonymous/anonymous/.vscode-oss/extensions/ms-dotnettools.csharp-2.0.249/dist/extension.js:2:1008463)
```

**Comment by GlacierFox** [comment] 2023-07-13 16:56
I'm getting this error too on Debian 12. I've manually installed dotnet and I'm trying to use the newly released MAUI extension.

**Comment by vlariono** [comment] 2023-07-13 18:39
Duplicate of #1007

**Comment by baronfel** [comment] 2023-07-17 14:11
Closing as duplicate.

**Closed by baronfel** 2023-07-17 14:11 UTC
